/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package splashscreen;


import gestion_snackbar.Utilisateur;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class Splash extends javax.swing.JFrame {

    /**
     * Creates new form Splash
     */
    public Splash() {
        initComponents();
       
    }
public void Imagetitle()
  {
      setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("title.png")));
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        charge = new javax.swing.JLabel();
        barCharger = new javax.swing.JProgressBar();
        pourcent = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AA Manager App");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splashscreen/reliability-2.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 560, 280));

        jLabel3.setFont(new java.awt.Font("Monospaced", 3, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText(" AA Manager App");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 470, 80));

        charge.setFont(new java.awt.Font("Sylfaen", 3, 14)); // NOI18N
        charge.setForeground(new java.awt.Color(255, 255, 255));
        charge.setText("Chargement.....");
        jPanel1.add(charge, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 310, 20));
        jPanel1.add(barCharger, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 760, 20));

        pourcent.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        pourcent.setForeground(new java.awt.Color(255, 255, 255));
        pourcent.setText("0%");
        jPanel1.add(pourcent, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, 40, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splashscreen/img2.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        Splash s=new Splash();
        s.setVisible(true);
        s.Imagetitle();
        try {
            
            for(int i=0;i<=100;i++)
            {
                
                Thread.sleep(100);
                s.barCharger.setValue(i);
                
                if(i==3)
                {
                    s.charge.setText("Chargement..");
                    s.pourcent.setText("3%");
                }
                if(i==5)
                {
                    s.charge.setText("Chargement....");
                    s.pourcent.setText("5%");
                }
                if(i==8)
                {
                    s.charge.setText("Chargement......");
                    s.pourcent.setText("8%");
                }
                if(i==10)
                {
                    s.charge.setText("Chargement........");
                    s.pourcent.setText("10%");
                }
                if(i==13)
                {
                    s.charge.setText("Chargement du programme...");
                    s.pourcent.setText("13%");
                }
                
                if(i==15)
                {
                    s.charge.setText("Chargement du programme.....");
                    s.pourcent.setText("15%");
                }
                if(i==18)
                {
                    s.charge.setText("Chargement du programme..");
                    s.pourcent.setText("18%");
                }
                if(i==25)
                {
                    s.charge.setText("Chargement du programme....");
                    s.pourcent.setText("25%");
                }
                if(i==27)
                {
                    s.charge.setText("Initialisation..");
                    s.pourcent.setText("27%");
                }
                if(i==29)
                {
                    s.charge.setText("Initialisation...");
                    s.pourcent.setText("29%");
                }
                if(i==31)
                {
                    s.charge.setText("Initialisation....");
                    s.pourcent.setText("31%");
                }
                if(i==33)
                {
                    s.charge.setText("Initialisation......");
                    s.pourcent.setText("33%");
                }
                if(i==35)
                {
                    s.charge.setText("Initialisation..");
                    s.pourcent.setText("35%");
                }
                if(i==38)
                {
                    s.charge.setText("Initialisation....");
                    s.pourcent.setText("30%");
                }
                if(i==39)
                {
                    s.charge.setText("....");
                    s.pourcent.setText("39%");
                }
                if(i==40) 
                {
                    s.charge.setText("......");
                    s.pourcent.setText("40%");
                }
                if(i==43)
                {
                    s.charge.setText("Initialisation..");
                    s.pourcent.setText("43%");
                }
                if(i==44)
                {
                    s.charge.setText("Initialisation en cours..");
                    s.pourcent.setText("44%");
                }
                if(i==45)
                {
                    s.charge.setText("Initialisation en cours....");
                    s.pourcent.setText("45%");
                }
                 if(i==50)
                {
                    s.charge.setText("Vérification du connexion..");
                    s.pourcent.setText("50%");
                }
                 if(i==54)
                {
                    s.charge.setText("Vérification du connexion....");
                    s.pourcent.setText("54%");
                }
                 if(i==59)
                {
                    s.charge.setText("Vérification du connexion......");
                    s.pourcent.setText("59%");
                }
                   if(i==64)
                {
                    s.charge.setText("..");
                    s.pourcent.setText("64%");
                }
                   if(i==65) 
                {
                    s.charge.setText("...");
                    s.pourcent.setText("66%");
                }
                   if(i==66)
                {
                    s.charge.setText("Vérification du connexion..");
                    s.pourcent.setText("64%");
                }
                   if(i==68)
                {
                    s.charge.setText("Vérification du connexion...");
                    s.pourcent.setText("64%");
                }
                    if(i==70)
                {
                    s.charge.setText("Vérification du connexion.....");
                    s.pourcent.setText("70%");
                }
                     if(i==72)
                {
                    s.charge.setText("..");
                    s.pourcent.setText("72%");
                }
                     if(i==73)
                {
                    s.charge.setText("....");
                    s.pourcent.setText("73%");
                }
                  if(i==75)
                {
                    s.charge.setText("Renvoie requête..");
                    s.pourcent.setText("75%");
                }
                   if(i==78)
                {
                    s.charge.setText("Renvoie du requête....");
                    s.pourcent.setText("78%");
                }
                    if(i==79)
                {
                    s.charge.setText("Renvoie du requête......");
                    s.pourcent.setText("79%");
                }
                    if(i==80)
                {
                    s.charge.setText("Requête en cours.....");
                    s.pourcent.setText("80%");
                }
                 
                    if(i==81)
                {
                    s.charge.setText("Requête en cours...");
                    s.pourcent.setText("82%");
                }
                    if(i==84)
                {
                    s.charge.setText("Requête en cours........");
                    s.pourcent.setText("84%");
                }
                     if(i==85)
                {
                     s.charge.setText("Reception..");
                    s.pourcent.setText("85%");
                }
                     if(i==86)
                {
                    s.charge.setText("PreOuverture des données..");
                    s.pourcent.setText("86%");
                }
                     if(i==87)
                {
                    s.charge.setText("PreOuverture des données.....");
                    s.pourcent.setText("87%");
                }
                  if(i==88)
                {
                    s.charge.setText("Récuperartion des données......");
                    s.pourcent.setText("88%");
                }  if(i==90)
                {
                   s.charge.setText("Récuperartion des données...");
                    s.pourcent.setText("90%");
                }
                if(i==94)
                {
                   s.charge.setText("Récuperartion des données......");
                    s.pourcent.setText("94%");
                }
                 if(i==96)
                {
                   s.charge.setText("Ouverture des données...");
                    s.pourcent.setText("96%");
                }
                 if(i==98)
                {
                   s.charge.setText("Ouverture des données.....");
                    s.pourcent.setText("98%");
                }
                   if(i==100)
                {
                    s.charge.setText("Fini...");
                    s.pourcent.setText("100%");
                }
                  
            }
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } 
        s.dispose();
        Utilisateur c=new Utilisateur();
        c.setVisible(true);
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barCharger;
    private javax.swing.JLabel charge;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pourcent;
    // End of variables declaration//GEN-END:variables
}
