/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_snackbar;

import ConnectionBD.Connexion;
import ConnectionBD.connectDatabase;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author pc
 */
public final class ProduitsEnStock extends javax.swing.JFrame {

    Connexion con =new Connexion();
    ConnectionBD.connectDatabase con2=new connectDatabase();
    Statement st;
    ResultSet rs;
    DefaultTableModel tb1=new DefaultTableModel();
    DefaultTableModel tb2=new DefaultTableModel();
    DefaultTableModel tb3=new DefaultTableModel();
    public ProduitsEnStock() {
        initComponents();
        tb1=(DefaultTableModel)jTable1.getModel();
        tb2=(DefaultTableModel)jTable2.getModel();
        tb3=(DefaultTableModel)jTable3.getModel();
        sett();
        ajout();
        t1();
        t2();
        t3();
        combproduit();
        combofour();
        serviteur();
        Imagetitle();
        numfour.setEditable(false);
        inputnump.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        priprof = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        nomprof = new javax.swing.JTextField();
        qtpro = new javax.swing.JTextField();
        numfour = new javax.swing.JTextField();
        numprof = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nomFo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        rechps = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        filtra2 = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        rechrp = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputnump = new javax.swing.JTextField();
        inputprix = new javax.swing.JTextField();
        nompr = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        filtra1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jour = new javax.swing.JTextField();
        mois = new javax.swing.JTextField();
        an = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        resulta1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        mois2 = new javax.swing.JTextField();
        an2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        mois3 = new javax.swing.JTextField();
        an3 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        rech3 = new javax.swing.JTextField();
        jButton18 = new javax.swing.JButton();
        filtra3 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        nomE = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        resulta2 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        datec = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Table des Produits");
        setResizable(false);

        jLayeredPane1.setBackground(new java.awt.Color(0, 102, 102));

        jTabbedPane1.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº du produit", "Nom du produit", "Nombre de gasier", "Prix d'Achat d'un gasier", "Nom du fournisseur", "Date d'enregistrement "
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        priprof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priprofActionPerformed(evt);
            }
        });
        priprof.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                priprofKeyReleased(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Documents\\NetBeansProjects\\Gestion_SnackBar\\src\\gestion_snackbar\\new1.png")); // NOI18N
        jButton8.setText("Modifier");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Documents\\NetBeansProjects\\Gestion_SnackBar\\src\\gestion_snackbar\\edit_add16.png")); // NOI18N
        jButton9.setText("Ajouter");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Documents\\NetBeansProjects\\Gestion_SnackBar\\src\\gestion_snackbar\\open.png")); // NOI18N
        jButton10.setText("Exporter");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        qtpro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtproKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qtproKeyTyped(evt);
            }
        });

        numfour.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        numfour.setForeground(new java.awt.Color(204, 0, 0));
        numfour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numfourMouseClicked(evt);
            }
        });
        numfour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numfourActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        jLabel1.setText("Insertion ");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel7.setFont(new java.awt.Font("Poor Richard", 1, 11)); // NOI18N
        jLabel7.setText("Numéro du produit");

        jLabel8.setFont(new java.awt.Font("Poor Richard", 1, 11)); // NOI18N
        jLabel8.setText("Numéro du fournisseur");

        nomFo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                nomFoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel9.setFont(new java.awt.Font("Poor Richard", 1, 11)); // NOI18N
        jLabel9.setText("Nom du produit");

        jLabel10.setFont(new java.awt.Font("Poor Richard", 1, 11)); // NOI18N
        jLabel10.setText("Nombre de gasier");

        jLabel11.setFont(new java.awt.Font("Poor Richard", 1, 11)); // NOI18N
        jLabel11.setText("Prix d'Achat d'un gasier");

        jButton11.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Documents\\NetBeansProjects\\Gestion_SnackBar\\src\\gestion_snackbar\\refresh1.png")); // NOI18N
        jButton11.setText("Actualiser");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Recherche");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Poor Richard", 1, 11)); // NOI18N
        jLabel12.setText("Nom du fournisseur");

        jLabel30.setFont(new java.awt.Font("Poor Richard", 1, 11)); // NOI18N
        jLabel30.setText("Recherche par Nº");

        jLabel31.setFont(new java.awt.Font("Poor Richard", 1, 11)); // NOI18N
        jLabel31.setText("Filtrer");

        filtra2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filtra2KeyReleased(evt);
            }
        });

        jButton17.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Documents\\NetBeansProjects\\Gestion_SnackBar\\src\\gestion_snackbar\\close_hover.png")); // NOI18N
        jButton17.setText("Supprimer");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        jLabel39.setText("Prix Total d'Achat :");

        total.setBackground(new java.awt.Color(102, 102, 102));
        total.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        total.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        total.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(18, 18, 18)
                        .addComponent(filtra2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rechps, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numprof)
                    .addComponent(nomFo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numfour)
                    .addComponent(nomprof)
                    .addComponent(qtpro)
                    .addComponent(priprof)
                    .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(128, 128, 128))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rechps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(filtra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomFo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numfour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numprof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(5, 5, 5)
                        .addComponent(nomprof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(1, 1, 1)
                        .addComponent(qtpro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel11)
                        .addGap(1, 1, 1)
                        .addComponent(priprof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );

        jTabbedPane1.addTab("Produits En Stock", jPanel2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº du produit", "Nom du  produit", "Prix de Vente Unitaire "
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        rechrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechrpActionPerformed(evt);
            }
        });

        jButton1.setText("Rechercher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Poor Richard", 1, 11)); // NOI18N
        jLabel2.setText("Recherche par Nº");

        jLabel3.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        jLabel3.setText("Insertion");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        inputnump.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        inputnump.setForeground(new java.awt.Color(204, 0, 0));
        inputnump.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputnumpMouseClicked(evt);
            }
        });
        inputnump.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputnumpActionPerformed(evt);
            }
        });

        nompr.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                nomprPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Documents\\NetBeansProjects\\Gestion_SnackBar\\src\\gestion_snackbar\\edit_add16.png")); // NOI18N
        jButton3.setText("Ajouter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Documents\\NetBeansProjects\\Gestion_SnackBar\\src\\gestion_snackbar\\close_hover.png")); // NOI18N
        jButton4.setText("Supprimer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Documents\\NetBeansProjects\\Gestion_SnackBar\\src\\gestion_snackbar\\new1.png")); // NOI18N
        jButton5.setText("Modifier");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Documents\\NetBeansProjects\\Gestion_SnackBar\\src\\gestion_snackbar\\open.png")); // NOI18N
        jButton6.setText("Explorter");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Poor Richard", 1, 11)); // NOI18N
        jLabel5.setText(" Nom du produit");

        jLabel6.setFont(new java.awt.Font("Poor Richard", 1, 11)); // NOI18N
        jLabel6.setText("Numéro du produit");

        jLabel4.setFont(new java.awt.Font("Poor Richard", 1, 11)); // NOI18N
        jLabel4.setText("Prix de vente Unitaire");

        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Documents\\NetBeansProjects\\Gestion_SnackBar\\src\\gestion_snackbar\\refresh1.png")); // NOI18N
        jButton7.setText("Actualiser");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Poor Richard", 1, 11)); // NOI18N
        jLabel32.setText("Filtrer");

        filtra1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filtra1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(filtra1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(rechrp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(37, 37, 37))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addContainerGap(278, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(nompr, javax.swing.GroupLayout.Alignment.LEADING, 0, 209, Short.MAX_VALUE)
                                    .addComponent(inputnump, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputprix, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nompr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputnump, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputprix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(filtra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rechrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
        );

        jTabbedPane1.addTab("Produits à Vendre", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));

        jLabel13.setBackground(new java.awt.Color(0, 51, 51));
        jLabel13.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Produits disponible pour vendre");
        jLabel13.setOpaque(true);

        jLabel14.setBackground(new java.awt.Color(0, 51, 51));
        jLabel14.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Statistique des commandes");
        jLabel14.setOpaque(true);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº produit", "Nom du produit", "Quantite restant", "Nombre initial de gasier", "Nombre initial de bouteille"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Documents\\NetBeansProjects\\Gestion_SnackBar\\src\\gestion_snackbar\\refresh1.png")); // NOI18N
        jButton2.setText("Actualiser");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton13.setText("Voir");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        an.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Poor Richard", 1, 11)); // NOI18N
        jLabel16.setText("Jour");

        jLabel17.setFont(new java.awt.Font("Poor Richard", 1, 11)); // NOI18N
        jLabel17.setText("Mois");

        jLabel18.setFont(new java.awt.Font("Poor Richard", 1, 11)); // NOI18N
        jLabel18.setText("An");

        resulta1.setBackground(new java.awt.Color(102, 102, 102));
        resulta1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 10)); // NOI18N
        resulta1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        resulta1.setOpaque(true);

        jLabel19.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jLabel19.setText("Voir le nombre de commandes ");

        jButton15.setText("Voir");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        jLabel20.setText("Voir le nombre de commandes ");

        jLabel21.setFont(new java.awt.Font("Poor Richard", 1, 11)); // NOI18N
        jLabel21.setText("Mois");

        jLabel22.setFont(new java.awt.Font("Poor Richard", 1, 11)); // NOI18N
        jLabel22.setText("An");

        jButton14.setText("Voir");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        jLabel23.setText("faites par Date specifique");

        jLabel24.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        jLabel24.setText("Voir le nombre de commandes");

        jLabel25.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        jLabel25.setText("faites par Mois ou Annee specifique");

        an3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                an3ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Poor Richard", 1, 11)); // NOI18N
        jLabel26.setText("Mois");

        jLabel27.setFont(new java.awt.Font("Poor Richard", 1, 11)); // NOI18N
        jLabel27.setText("An");

        jButton16.setText("Voir");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        jLabel28.setText("faites par Mois et Annee specifique");

        jLabel29.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        jLabel29.setText("Resultat  :");

        jLabel15.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        jLabel15.setText("Resultat :");

        jButton18.setText("Rechercher");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        filtra3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filtra3KeyReleased(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Poor Richard", 1, 11)); // NOI18N
        jLabel33.setText("Filtrer");

        jLabel34.setFont(new java.awt.Font("Poor Richard", 1, 11)); // NOI18N
        jLabel34.setText("Recherche par Nº");

        jLabel35.setBackground(new java.awt.Color(0, 51, 51));
        jLabel35.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Voir combien des commandes");
        jLabel35.setOpaque(true);

        jLabel36.setBackground(new java.awt.Color(0, 51, 51));
        jLabel36.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText(" ont fait les serviteurs ");
        jLabel36.setOpaque(true);

        jLabel37.setFont(new java.awt.Font("Serif", 1, 11)); // NOI18N
        jLabel37.setText("Nom d'Employe");

        jLabel38.setFont(new java.awt.Font("Serif", 1, 11)); // NOI18N
        jLabel38.setText("Date [yyyy-mm-dd] ");

        resulta2.setBackground(new java.awt.Color(102, 102, 102));
        resulta2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 10)); // NOI18N
        resulta2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        resulta2.setOpaque(true);

        jButton19.setText("Afficher");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        datec.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                datecFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                datecFocusLost(evt);
            }
        });
        datec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(resulta1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nomE, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel37)
                                .addComponent(jLabel15)
                                .addComponent(resulta2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                        .addComponent(datec, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton19))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filtra3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rech3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jButton18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(404, 404, 404))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel17))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel18)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mois, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(an, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton13)))))
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jour, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel21)
                                                .addGap(8, 8, 8))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(an2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mois2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20))))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(an3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton16))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mois3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton15)))
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(239, 239, 239))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rech3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel33)
                                .addComponent(filtra3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel34)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel37)
                        .addGap(2, 2, 2)
                        .addComponent(nomE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel38)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton19)
                            .addComponent(datec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(resulta2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(mois3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton15)
                            .addComponent(mois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(an3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton16)
                                    .addComponent(jLabel27)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(an, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton13)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel24))
                                .addGap(3, 3, 3)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel28))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(mois2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(an2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22)
                                    .addComponent(jButton14)))
                            .addComponent(resulta1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Controle", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       
        ProduitsEnStock pr=new ProduitsEnStock();
        pr.setVisible(true);
        dispose();
       
    }//GEN-LAST:event_jButton11ActionPerformed

    private void numfourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numfourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numfourActionPerformed

    private void numfourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numfourMouseClicked
       
    }//GEN-LAST:event_numfourMouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String q="insert into produitstock (numProduit,numFour,nomProduit,quantiteGazier,prixAchatGazier) values ("+numprof.getText()+","+numfour.getText()+",'"+nomprof.getText()+"',"+qtpro.getText()+","+priprof.getText()+")";
        
        try {
             st=con.connecion().createStatement();
             st.executeUpdate(q);            
              actuel();
              JOptionPane.showMessageDialog(rootPane, "Insertion réussie !");
              setps();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       int selected=jTable2.getSelectedRow();
        String cli=(jTable2.getModel().getValueAt(selected,0).toString());
        String mo="update produitstock set numProduit="+numprof.getText()+",numFour="+numfour.getText()+",nomProduit='"+nomprof.getText()+"',quantiteGazier="+qtpro.getText()+",prixAchatGazier="+priprof.getText()+" where numProduit="+cli+"";
        
        try {
              st=con.connecion().createStatement();
              if(JOptionPane.showConfirmDialog(this,"Voulez-vous modifier ?",null,JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION)
              {
                  tb2.setRowCount(0);
                  st.execute(mo);               
                  actuel();
                  JOptionPane.showMessageDialog(rootPane," Modification réussie !");
                  setps();
              }   
           } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,ex);
        }
       
    }//GEN-LAST:event_jButton8ActionPerformed

    private void priprofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priprofActionPerformed
           
    }//GEN-LAST:event_priprofActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
        ProduitsEnStock pr=new ProduitsEnStock();
        pr.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int selected=jTable1.getSelectedRow();
        String cli=(jTable1.getModel().getValueAt(selected,0).toString());       
        String m="update produit set numProduit="+inputnump.getText()+",nomProduit='"+nompr.getSelectedItem()+"',prixVenteUnitaire="+inputprix.getText()+" where numProduit="+cli+"";
        
        try {
            st=con.connecion().createStatement();
            if(JOptionPane.showConfirmDialog(rootPane,"Voulez-vous modification ?",null,JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION)
            {
                
                st.executeUpdate(m);
                actuel();
                JOptionPane.showMessageDialog(null," Modification réussie !");
                sett();
                //rechrp.setText("");
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int selected=jTable1.getSelectedRow();
        String cli=(jTable1.getModel().getValueAt(selected,0).toString());
        String su="delete from produit where numProduit="+cli+"";
        
        try {
           
            st=con.connecion().createStatement();
            if(JOptionPane.showConfirmDialog(rootPane,"Voulez-vous supprimer ?",null,JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION)
            {
                st.executeUpdate(su);
                actuel();
                JOptionPane.showMessageDialog(rootPane,"Suppression réussie !");
                sett();
                
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,ex);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String i="insert into produit values ("+inputnump.getText()+",'"+nompr.getSelectedItem()+"',"+inputprix.getText()+")";
       
        try {
            st=con.connecion().createStatement();
            st.executeUpdate(i);
            //ajout();
            actuel();
            JOptionPane.showMessageDialog(rootPane, "Insertion réussie");
            sett();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void inputnumpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputnumpActionPerformed

    }//GEN-LAST:event_inputnumpActionPerformed

    private void inputnumpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputnumpMouseClicked
       
    }//GEN-LAST:event_inputnumpMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       String y=rechrp.getText();
       for(int i=1;i<jTable1.getRowCount();i++)
       {
           if (jTable1.getValueAt(i,0).equals(y))
           {
               jTable1.setRowSelectionInterval(i, i);
           }
       }
       
        String g="select * from produit where numProduit="+y+"";
        try {
              st=con.connecion().createStatement();
              rs=st.executeQuery(g);
            if(rs.next())
            {
                nompr.setSelectedItem(rs.getString("nomProduit"));
                inputnump.setText(rs.getString("numProduit"));
                inputprix.setText(rs.getString("prixVenteUnitaire"));
            }
            else
            JOptionPane.showMessageDialog(rootPane," N'existe pas !");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void rechrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechrpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rechrpActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
      String ps=rechps.getText();
       for(int i=0;i<jTable2.getRowCount();i++)
       {
           if (jTable2.getValueAt(i,0).equals(ps))
           {
               jTable2.setRowSelectionInterval(i, i);
           }
       }

        String gf="select * from produitstock,fournisseur where numProduit="+ps+" and produitstock.numFour=fournisseur.numFour";
        try {
            st=con.connecion().createStatement();
            rs=st.executeQuery(gf);
            if(rs.next())
            {
                numprof.setText(rs.getString("numProduit"));
                numfour.setText(rs.getString("fournisseur.numFour"));
                nomFo.setSelectedItem(rs.getString("nomFour"));
                nomprof.setText(rs.getString("nomProduit"));
                qtpro.setText(rs.getString("quantiteGazier"));
                priprof.setText(rs.getString("prixAchatGazier"));
                
            }
            else
            JOptionPane.showMessageDialog(rootPane," N'existe pas !");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,ex);
        }
        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
      Export_Excel f=new Export_Excel(jTable2,this);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        try {
            
             
                 rs=con2.extaireData("select concat(count(numCommande),' Commandes') as 'resultat' from commande where month(date)="+mois.getText()+" and year(date)="+an.getText()+"");
                 while(rs.next())
                 resulta1.setText(rs.getString("resultat"));
           
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Echec !");
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void an3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_an3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_an3ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
       try {
            
             
                 rs=con2.extaireData("select concat(count(numCommande),' Commandes') as 'resultat' from commande where year(date)="+an3.getText()+"");
                 while(rs.next())
                 resulta1.setText(rs.getString("resultat"));
           
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Echec !");
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void anActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        try {
            
             
                 rs=con2.extaireData("select concat(count(numCommande),' Commandes') as 'resultat' from commande where day(date)="+jour.getText()+" and month(date)="+mois2.getText()+" and year(date)="+an2.getText()+"");
                 while(rs.next())
                 resulta1.setText(rs.getString("resultat"));
           
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Echec !");
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        try {
            
             
                 rs=con2.extaireData("select concat(count(numCommande),' Commandes') as 'resultat' from commande where month(date)="+mois3.getText()+"");
                 while(rs.next())
                 resulta1.setText(rs.getString("resultat"));
           
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Echec !");
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
       ProduitsEnStock ps=new ProduitsEnStock();
       ps.setVisible(true);       
       dispose();
                
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int row=jTable2.getSelectedRow();
        String cli=(jTable2.getModel().getValueAt(row,0).toString());
        String gf="select * from produitstock,fournisseur where numProduit="+cli+" and produitstock.numFour=fournisseur.numFour";
        try {
            st=con.connecion().createStatement();
            rs=st.executeQuery(gf);
            if(rs.next())
            {
                numprof.setText(rs.getString("numProduit"));
                numfour.setText(rs.getString("fournisseur.numFour"));
                nomFo.setSelectedItem(rs.getString("nomFour"));
                nomprof.setText(rs.getString("nomProduit"));
                qtpro.setText(rs.getString("quantiteGazier"));
                priprof.setText(rs.getString("prixAchatGazier"));
                
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane," Echec !");
        }
        total();
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row=jTable1.getSelectedRow();
        String cli=(jTable1.getModel().getValueAt(row,0).toString());
        String g="select * from produit where numProduit="+cli+"";
        try {
              st=con.connecion().createStatement();
              rs=st.executeQuery(g);
            if(rs.next())
            {
                nompr.setSelectedItem(rs.getString("nomProduit"));
                inputnump.setText(rs.getString("numProduit"));
                inputprix.setText(rs.getString("prixVenteUnitaire"));
            }
            else
            JOptionPane.showMessageDialog(rootPane," N'existe pas !");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane," Echec !");
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        int selected=jTable2.getSelectedRow();
        String cli=(jTable2.getModel().getValueAt(selected,0).toString());
        String query="delete from produitstock where numProduit="+cli+"";
        
        try {
            if(JOptionPane.showConfirmDialog(rootPane,"Voulez-vous supprimer ?",null,JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION)
            {
               
                st=con.connecion().createStatement();
                st.execute(query);
                actuel();
                JOptionPane.showMessageDialog(rootPane," Suppression réussie !");
                setps();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,ex);
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void filtra2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtra2KeyReleased
        String b=filtra2.getText();
        filtrer2(b);
    }//GEN-LAST:event_filtra2KeyReleased

    private void filtra1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtra1KeyReleased
        String a=filtra1.getText();
        filtrer1(a);
    }//GEN-LAST:event_filtra1KeyReleased

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        String r=rech3.getText();
             for(int i=0;i<jTable3.getRowCount();i++)
             {
                 if(jTable3.getValueAt(i,0).equals(r))
                     jTable3.setRowSelectionInterval(i, i);
             }
        
    }//GEN-LAST:event_jButton18ActionPerformed

    private void filtra3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtra3KeyReleased
        String d=filtra3.getText();
        filtrer3(d);
    }//GEN-LAST:event_filtra3KeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Export_Excel f=new Export_Excel(jTable1,this);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        String a="select count(numCommande) from commande,employe where  id=idCommande and nomEmploye='"+nomE.getSelectedItem()+"' and commande.date like'"+datec.getText()+"%' ";
        try {
            st=con.connecion().createStatement();
            rs=st.executeQuery(a);
            while(rs.next())
                resulta2.setText(rs.getString("count(numCommande)")+" Commandes");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        
    }//GEN-LAST:event_jButton19ActionPerformed

    private void priprofKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priprofKeyReleased
        total();
    }//GEN-LAST:event_priprofKeyReleased

    private void qtproKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtproKeyTyped
        
    }//GEN-LAST:event_qtproKeyTyped

    private void qtproKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtproKeyReleased
        total();
    }//GEN-LAST:event_qtproKeyReleased

    private void datecFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_datecFocusLost
     
    }//GEN-LAST:event_datecFocusLost

    private void datecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datecActionPerformed

    private void datecFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_datecFocusGained
       
    }//GEN-LAST:event_datecFocusGained

    private void nomprPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_nomprPopupMenuWillBecomeInvisible
         String q="select * from produitstock where nomProduit='"+nompr.getSelectedItem()+"'";
        try {
            st=con.connecion().createStatement();
            rs=st.executeQuery(q);
            while(rs.next())
            inputnump.setText(rs.getString("numProduit"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane," Echec !");
        }
    }//GEN-LAST:event_nomprPopupMenuWillBecomeInvisible

    private void nomFoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_nomFoPopupMenuWillBecomeInvisible
         String fo="select * from fournisseur where nomfour='"+nomFo.getSelectedItem()+"'";
        try {
            st=con.connecion().createStatement();
            rs=st.executeQuery(fo);
            while(rs.next())
            numfour.setText(rs.getString("numFour"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,ex);
        }
    }//GEN-LAST:event_nomFoPopupMenuWillBecomeInvisible
public void combproduit()
{
    String se="select * from produitstock order by numProduit desc";
        try {
            nompr.setSelectedItem(0);
            st=con.connecion().createStatement();
            rs=st.executeQuery(se);
            while(rs.next())
                nompr.addItem(rs.getString("nomProduit"));
        } catch (Exception ex) {
           //JOptionPane.showMessageDialog(rootPane,ex); 
        }
        
}
public void t1()
{
    String t1="select * from produit order by numProduit desc";
        try {
            st=con.connecion().createStatement();
            rs=st.executeQuery(t1);
            tb1.setRowCount(0);
            while(rs.next())
            {
                
                tb1.addRow(new Object[]{
                
                rs.getString("numProduit"),
                rs.getString("nomProduit"),
                rs.getString("prixVenteUnitaire")
              });
  
            }
        } catch (Exception ex) {
            //JOptionPane.showMessageDialog(rootPane,ex);
        }
    
}

public void sett()
{
    inputnump.setText("");
    inputprix.setText("");
}
public void ajout()
{
    String nump,nomp,prx;
    nump=(String) nompr.getSelectedItem();
    nomp=inputnump.getText();
    prx=inputprix.getText();
    String[] ligne=new String[]{nump,nomp,prx};
    tb1.addRow(ligne);
}

 public void t2()
 {
     String af="select * from produitstock,fournisseur where fournisseur.numFour=produitstock.numFour order by numProduit desc";
        try {
            st=con.connecion().createStatement();
            rs=st.executeQuery(af);
            tb2.setRowCount(0);
            while(rs.next())
            {
                tb2.addRow(new Object[]{
                rs.getString("numProduit"),
                rs.getString("nomProduit"),
                rs.getString("quantiteGazier"),
                rs.getString("prixAchatGazier"),
                rs.getString("nomFour"),
                rs.getString("dateAchat")
                });
            }
        } catch (Exception ex) {
            //JOptionPane.showMessageDialog(rootPane,ex);
        }          
 }
 public void combofour()
 {
      String affou="select * from fournisseur";
        try {
            nomFo.setSelectedItem(0);
            st=con.connecion().createStatement();
            rs=st.executeQuery(affou);
            while(rs.next())
                nomFo.addItem(rs.getString("nomFour"));
            
            }
         catch (Exception ex) {
           // JOptionPane.showMessageDialog(rootPane,ex);
        }          
 }
 public void effacertb1()
 {
      while(tb1.getRowCount()>0)
        {
            for(int i=0;i<tb1.getRowCount();i++)
                
            tb1.removeRow(i);
            
        }
 }
 public void effacertb2()
 {
    while(tb2.getRowCount()>0)
        {
            for(int i=0;i<tb2.getRowCount();i++)
                
            tb2.removeRow(i);
            
        } 
 }
 public void actuel()
 { 
     
     //effacertb2();
     t2();
     //effacertb1();
     t1();
 }
 
 public void setps()
 {
     numprof.setText("");
     qtpro.setText("");
     priprof.setText("");
     nomprof.setText("");
 }
   public void t3()
   {
       String t="select (quantiteGazier*12) as 'NbdeBouteille',quantiteGazier,(((quantiteGazier*12)-sum(quantite))) as 'quantite_restant',detail.numProduit,nomProduit from produitstock,detail where produitstock.numProduit=detail.numProduit group by produitstock.numProduit order by produitstock.numProduit asc";
        tb3.setRowCount(0);
       try {
            st=con.connecion().createStatement();
            rs=st.executeQuery(t);
            while(rs.next())
            {
                tb3.addRow(new Object[]{
                rs.getString("detail.numProduit"),
                rs.getString("nomProduit"),
                rs.getString("quantite_restant"),
                rs.getString("quantiteGazier"),
                rs.getString("NbdeBouteille")
                   
                
                });
            }
        } catch (Exception ex) {
           // JOptionPane.showMessageDialog(null, ex);
        }
   }
   public void filtrer1(String ecris)
   {
       TableRowSorter<DefaultTableModel> p=new TableRowSorter<>(tb1);
       jTable1.setRowSorter(p);
       p.setRowFilter(RowFilter.regexFilter(ecris));
   }
   public void filtrer2(String write)
   {
       TableRowSorter<DefaultTableModel> ps=new TableRowSorter<>(tb2);
       jTable2.setRowSorter(ps);
       ps.setRowFilter(RowFilter.regexFilter(write));
   }
   public void filtrer3(String write)
   {
       TableRowSorter<DefaultTableModel> b=new TableRowSorter<>(tb3);
       jTable3.setRowSorter(b);
       b.setRowFilter(RowFilter.regexFilter(write));
   }
   
   public void serviteur()
   {
       String e="select nomEmploye from employe ";
        try {
            st=con.connecion().createStatement();
            rs=st.executeQuery(e);
            while(rs.next())
                nomE.addItem(rs.getString("nomEmploye"));
        } catch (Exception ex) {
           // JOptionPane.showMessageDialog(rootPane, ex); 
        }
       
   }
   public void Imagetitle()
  {
      setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("title.png")));
  }
   public void total()
   {
       if(qtpro.getText().isEmpty() && priprof.getText().isEmpty())
       {
           total.setText(""+0);
       }
       else if(qtpro.getText().isEmpty() || priprof.getText().isEmpty()) {
           total.setText(""+0);
           
       } 
        else 
           {
       
             long  a=Long.parseLong(qtpro.getText());
             long  b=Long.parseLong(priprof.getText());
             long c=a*b;
             total.setText(""+c);
           }
   }
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProduitsEnStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProduitsEnStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProduitsEnStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProduitsEnStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProduitsEnStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField an;
    private javax.swing.JTextField an2;
    private javax.swing.JTextField an3;
    private javax.swing.JTextField datec;
    private javax.swing.JTextField filtra1;
    private javax.swing.JTextField filtra2;
    private javax.swing.JTextField filtra3;
    private javax.swing.JTextField inputnump;
    private javax.swing.JTextField inputprix;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jour;
    private javax.swing.JTextField mois;
    private javax.swing.JTextField mois2;
    private javax.swing.JTextField mois3;
    private javax.swing.JComboBox<String> nomE;
    private javax.swing.JComboBox<String> nomFo;
    private javax.swing.JComboBox<String> nompr;
    private javax.swing.JTextField nomprof;
    private javax.swing.JTextField numfour;
    private javax.swing.JTextField numprof;
    private javax.swing.JTextField priprof;
    private javax.swing.JTextField qtpro;
    private javax.swing.JTextField rech3;
    private javax.swing.JTextField rechps;
    private javax.swing.JTextField rechrp;
    private javax.swing.JLabel resulta1;
    private javax.swing.JLabel resulta2;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
